### PR TITLE
sshtunnel/helm: use correct custom flag to enable/disable helm tunnel (fix)

### PR DESCRIPTION
**Pull request by sk4zuzu**

### CODE REVIEW

**Review by atsikham — APPROVED** [review]

**Review by to-bar — APPROVED** [review]

**Review by to-bar — CHANGES_REQUESTED** [review]
Please update changelog.

**Comment by atsikham** [comment]
> Please update changelog.

Do we need to do that if there is no task related to PR? Or it isn't so?

**Comment by to-bar** [comment]
> 
> 
> > Please update changelog.
> 
> Do we need to do that if there is no task related to PR? Or it isn't so?

I've noticed that there is linked task #1865.

**Comment by sk4zuzu** [comment]
@to-bar there is no need for adding changelog because this is the first time we release that feature. :+1::innocent:

**Review by to-bar — APPROVED** [review]

**Comment by to-bar** [comment]
> 
> 
> @to-bar there is no need for adding changelog because this is the first time we release that feature. 👍😇

OK, so then I approve.

**Pull request merged**
