### PR TITLE
Remove support for obsolete versions (< 0.7.0)

### PR DESCRIPTION
**Pull request by atsikham**
Task #2179.

Changes:
* moved K8s upgrade version check from roles/upgrade/tasks/kubernetes.yml to preflight
* removed parts related to versions <0.7.0

### CODE REVIEW

**Review by seriva — APPROVED** [review]

**Review by seriva — COMMENTED** [review]
Pressed the wrong review:)

**Review by seriva — DISMISSED** [review]

**Comment by seriva** [comment]
**Are all changes necessary or we would prefer leaving anything as it is?**
I think removing everything related to older versions is good.

**Does documentation need to be updated with any deprecation statement?**
IMO no as we dont expect people to install older version of K8s with the newest right, only maybe upgrade.

**Is it necessary to move existing K8s upgrade version check from roles/upgrade/tasks/kubernetes.yml to preflight?**
TBH not sure.

**Comment by to-bar** [comment]
**Is it necessary to move existing K8s upgrade version check from roles/upgrade/tasks/kubernetes.yml to preflight?**
IMO it's always better to check early when possible.

**Review by seriva — DISMISSED** [review]

**Review by to-bar — DISMISSED** [review]
:heart_eyes:

**Review by to-bar — DISMISSED** [review]

**Comment by przemyslavic** [comment]
@atsikham it fails when upgrading with an error: `open /etc/kubernetes/admin.conf: permission denied` 😢 
```
2021-05-18T08:40:52.6365198Z[38;21m08:40:52 INFO cli.engine.ansible.AnsibleCommand - TASK [preflight : Get K8s cluster version] *************************************
2021-05-18T08:40:53.5746533Z[31;21m08:40:53 ERROR cli.engine.ansible.AnsibleCommand - fatal: [ec2-1-1-1-1.eu-west-1.compute.amazonaws.com -> 1.1.1.1]: FAILED! => {"changed": false, "cmd": ["kubectl", "version", "--output", "yaml"], "delta": "0:00:00.056176", "end": "2021-05-18 08:40:53.473160", "msg": "non-zero return code", "rc": 1, "start": "2021-05-18 08:40:53.416984", "stderr": "error: error loading config file \"/etc/kubernetes/admin.conf\": open /etc/kubernetes/admin.conf: permission denied", "stderr_lines": ["error: error loading config file \"/etc/kubernetes/admin.conf\": open /etc/kubernetes/admin.conf: permission denied"], "stdout": "", "stdout_lines": []}
```

**Review by przemyslavic — APPROVED** [review]

**Comment by przemyslavic** [comment]
👍

**Review by rpudlowski93 — APPROVED** [review]

**Pull request merged**
