### PR TITLE
Hotfix: removing hard dependency on Helm

### PR DESCRIPTION
**Pull request by sk4zuzu**

### CODE REVIEW

**Comment by mkyc** [comment]
Does it solve some issue? Should it be linked?

**Comment by sk4zuzu** [comment]
Yes it solves the issue. It was a mutli level problem really (including other not reported cases), so this PR contains more code. :+1:

**Comment by mkyc** [comment]
I mean which issue. Should we link it to one of issues?

**Comment by mkyc** [comment]
Yeah, sorry I didn't noticed links.

**Comment by sk4zuzu** [comment]
The "official" issue it solves is linked to this PR #1349, but also the other #1334 becomes redundant I guess.

**Pull request merged**
