### PR TITLE
Extend k8s schema validation

### PR DESCRIPTION
**Pull request by atsikham**
As discussed with @seriva, there is no possibility for now to check additional fields and that's done by purpose and such behavior was requested before.

So this PR is only about schema extension with a basic validation.

### CODE REVIEW

**Review by seriva — DISMISSED** [review]

**Review by erzetpe — DISMISSED** [review]

**Comment by przemyslavic** [comment]
@atsikham validation for min and max values for certificate `expiration_days` doesn't seem to work, looks like only type is verified.
```
          expiration_days:
            title: expiration_days schema
            "$id": "#/properties/specification/properties/advanced/properties/certificates/properties/expiration_days"
            description: |-
              Days to make certificate be valid for.
              For more explanation about the limit navigate to
              https://groups.google.com/g/mailing.openssl.users/c/3kK_f0ywCZQ.
            type: integer
            minimum: 1
            maximum: 24855
            default: 365
```

**Comment by przemyslavic** [comment]
@seriva do you have any idea why it works a bit weird?
When I change the data type for expiration_date to string or whatever, it will fail right away:

```
epiuser@685a39ead66c:/shared$ epicli apply -f /shared/k8svalidate.yml --vault-password x
12:23:35 INFO cli.engine.schema.DefaultMerger - Starting step
12:23:35 INFO cli.engine.schema.DefaultMerger - Merging: epiphany-cluster name: default
12:23:35 INFO cli.engine.schema.DefaultMerger - Merging: configuration/kubernetes-master name: default
12:23:35 INFO cli.engine.schema.DefaultMerger - Step finished in: 0.04s
12:23:35 ERROR epicli - Types of key "expiration_days" are different: <class 'int'>, <class 'str'>. Unable to merge.
```

and when setting a number outside the range 1-24855 it fails after terraform 😨 
```
epiuser@685a39ead66c:/shared$ epicli apply -f /shared/k8svalidate.yml --vault-password x
12:25:21 INFO cli.engine.schema.DefaultMerger - Starting step
12:25:21 INFO cli.engine.schema.DefaultMerger - Merging: epiphany-cluster name: default
12:25:21 INFO cli.engine.schema.DefaultMerger - Merging: configuration/kubernetes-master name: default
12:25:21 INFO cli.engine.schema.DefaultMerger - Step finished in: 0.04s
12:25:21 INFO cli.engine.schema.SchemaValidator - Starting step
12:25:21 INFO cli.engine.schema.SchemaValidator - Validating: epiphany-cluster - k8svalidate
12:25:21 INFO cli.engine.schema.SchemaValidator - Step finished in: 0.04s
12:25:21 INFO cli.engine.providers.aws.InfrastructureBuilder - Starting step
12:25:23 INFO cli.engine.providers.aws.InfrastructureBuilder - Step finished in: 1.79s
12:25:23 INFO cli.engine.schema.SchemaValidator - Starting step
12:25:23 INFO cli.engine.schema.SchemaValidator - Validating: infrastructure/public-key - ubuntu
12:25:23 INFO cli.engine.schema.SchemaValidator - Validating: infrastructure/vpc - qa-k8svalidate-vpc
12:25:23 INFO cli.engine.schema.SchemaValidator - Validating: infrastructure/default-security-group - default-security-group
12:25:23 INFO cli.engine.schema.SchemaValidator - Validating: infrastructure/resource-group - qa-k8svalidate-rg
12:25:23 INFO cli.engine.schema.SchemaValidator - Validating: infrastructure/internet-gateway - qa-k8svalidate-internet-gateway
12:25:23 INFO cli.engine.schema.SchemaValidator - Validating: infrastructure/route-table - qa-k8svalidate-route-table
12:25:23 INFO cli.engine.schema.SchemaValidator - Validating: infrastructure/subnet - qa-k8svalidate-kubernetes-master-subnet-0
12:25:23 INFO cli.engine.schema.SchemaValidator - Validating: infrastructure/security-group - qa-k8svalidate-kubernetes-master-security-group-0
12:25:23 INFO cli.engine.schema.SchemaValidator - Validating: infrastructure/route-table-association - qa-k8svalidate-kubernetes-master-0-route-association
12:25:23 INFO cli.engine.schema.SchemaValidator - Validating: infrastructure/subnet - qa-k8svalidate-kubernetes-master-subnet-1
12:25:23 INFO cli.engine.schema.SchemaValidator - Validating: infrastructure/security-group - qa-k8svalidate-kubernetes-master-security-group-1
12:25:23 INFO cli.engine.schema.SchemaValidator - Validating: infrastructure/route-table-association - qa-k8svalidate-kubernetes-master-1-route-association
12:25:23 INFO cli.engine.schema.SchemaValidator - Validating: infrastructure/virtual-machine - qa-k8svalidate-kubernetes-master-asg-0
12:25:23 INFO cli.engine.schema.SchemaValidator - Validating: infrastructure/launch-configuration - qa-k8svalidate-kubernetes-master-launch-config
12:25:23 INFO cli.engine.schema.SchemaValidator - Validating: infrastructure/subnet - qa-k8svalidate-repository-subnet-0
12:25:23 INFO cli.engine.schema.SchemaValidator - Validating: infrastructure/security-group - qa-k8svalidate-repository-security-group-0
12:25:23 INFO cli.engine.schema.SchemaValidator - Validating: infrastructure/route-table-association - qa-k8svalidate-repository-0-route-association
12:25:23 INFO cli.engine.schema.SchemaValidator - Validating: infrastructure/virtual-machine - qa-k8svalidate-repository-asg-0
12:25:23 INFO cli.engine.schema.SchemaValidator - Validating: infrastructure/launch-configuration - qa-k8svalidate-repository-launch-config
12:25:23 INFO cli.engine.schema.SchemaValidator - Validating: infrastructure/efs-storage - qa-k8svalidate-efs
12:25:23 INFO cli.engine.schema.SchemaValidator - Step finished in: 0.26s
12:25:23 INFO cli.engine.terraform.TerraformTemplateGenerator - Starting step
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: epiphany-cluster ---> 000_k8svalidate.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: infrastructure/public-key ---> 001_ubuntu.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: infrastructure/vpc ---> 002_qa-k8svalidate-vpc.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: infrastructure/default-security-group ---> 003_default-security-group.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: infrastructure/resource-group ---> 004_qa-k8svalidate-rg.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: infrastructure/internet-gateway ---> 005_qa-k8svalidate-internet-gateway.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: infrastructure/route-table ---> 006_qa-k8svalidate-route-table.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: infrastructure/subnet ---> 007_qa-k8svalidate-kubernetes-master-subnet-0.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: infrastructure/security-group ---> 008_qa-k8svalidate-kubernetes-master-security-group-0.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: infrastructure/route-table-association ---> 009_qa-k8svalidate-kubernetes-master-0-route-association.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: infrastructure/subnet ---> 010_qa-k8svalidate-kubernetes-master-subnet-1.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: infrastructure/security-group ---> 011_qa-k8svalidate-kubernetes-master-security-group-1.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: infrastructure/route-table-association ---> 012_qa-k8svalidate-kubernetes-master-1-route-association.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: infrastructure/virtual-machine ---> 013_qa-k8svalidate-kubernetes-master-asg-0.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: infrastructure/launch-configuration ---> 014_qa-k8svalidate-kubernetes-master-launch-config.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: infrastructure/subnet ---> 015_qa-k8svalidate-repository-subnet-0.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: infrastructure/security-group ---> 016_qa-k8svalidate-repository-security-group-0.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: infrastructure/route-table-association ---> 017_qa-k8svalidate-repository-0-route-association.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: infrastructure/virtual-machine ---> 018_qa-k8svalidate-repository-asg-0.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: infrastructure/launch-configuration ---> 019_qa-k8svalidate-repository-launch-config.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Generating: infrastructure/efs-storage ---> 020_qa-k8svalidate-efs.tf
12:25:24 INFO cli.engine.terraform.TerraformTemplateGenerator - Step finished in: 0.26s
12:25:24 INFO cli.engine.terraform.TerraformFileCopier - Starting step
12:25:24 INFO cli.engine.terraform.TerraformFileCopier - Step finished in: 0.00s
12:25:24 INFO cli.engine.terraform.TerraformCommand - Running: "terraform -chdir=/shared/build/k8svalidate/terraform/ init -no-color"
12:25:24 INFO cli.engine.terraform.TerraformCommand -
12:25:24 INFO cli.engine.terraform.TerraformCommand - Initializing the backend...
12:25:26 INFO cli.engine.terraform.TerraformCommand -
12:25:26 INFO cli.engine.terraform.TerraformCommand - Initializing provider plugins...
12:25:26 INFO cli.engine.terraform.TerraformCommand - - Reusing previous version of hashicorp/aws from the dependency lock file
12:25:28 INFO cli.engine.terraform.TerraformCommand - - Using previously-installed hashicorp/aws v3.71.0
12:25:28 INFO cli.engine.terraform.TerraformCommand -
12:25:28 INFO cli.engine.terraform.TerraformCommand - Done running "terraform -chdir=/shared/build/k8svalidate/terraform/ init -no-color"
12:25:28 INFO cli.engine.terraform.TerraformCommand - Terraform has been successfully initialized!
12:25:28 INFO cli.engine.terraform.TerraformRunner - Starting step
12:25:28 INFO cli.engine.terraform.TerraformCommand -
12:25:28 INFO cli.engine.terraform.TerraformCommand - Running: "terraform -chdir=/shared/build/k8svalidate/terraform/ apply -state=/shared/build/k8svalidate/terraform//terraform.tfstate -auto-approve -no-color"
12:25:28 INFO cli.engine.terraform.TerraformCommand - You may now begin working with Terraform. Try running "terraform plan" to see
12:25:28 INFO cli.engine.terraform.TerraformCommand - any changes that are required for your infrastructure. All Terraform commands
12:25:28 INFO cli.engine.terraform.TerraformCommand - should now work.

terraform part

12:25:45 INFO cli.engine.terraform.TerraformCommand -
12:25:45 INFO cli.engine.terraform.TerraformCommand - Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
12:25:45 INFO cli.engine.terraform.TerraformCommand - Done running "terraform -chdir=/shared/build/k8svalidate/terraform/ apply -state=/shared/build/k8svalidate/terraform//terraform.tfstate -auto-approve -no-color"
12:25:45 INFO cli.engine.terraform.TerraformRunner - Step finished in: 17.56s
12:25:45 INFO cli.engine.schema.ConfigurationAppender - Starting step
12:25:45 INFO cli.engine.schema.ConfigurationAppender - Adding: configuration/feature-mapping
12:25:45 INFO cli.engine.schema.ConfigurationAppender - Adding: configuration/shared-config
12:25:45 INFO cli.engine.schema.ConfigurationAppender - Adding: configuration/helm
12:25:45 INFO cli.engine.schema.ConfigurationAppender - Adding: configuration/applications
12:25:45 INFO cli.engine.schema.ConfigurationAppender - Adding: configuration/node-exporter
12:25:45 INFO cli.engine.schema.ConfigurationAppender - Adding: configuration/filebeat
12:25:45 INFO cli.engine.schema.ConfigurationAppender - Adding: configuration/firewall
12:25:45 INFO cli.engine.schema.ConfigurationAppender - Adding: configuration/repository
12:25:45 INFO cli.engine.schema.ConfigurationAppender - Adding: configuration/image-registry
12:25:45 INFO cli.engine.schema.ConfigurationAppender - Step finished in: 0.19s
12:25:45 INFO cli.engine.schema.SchemaValidator - Starting step
12:25:45 INFO cli.engine.schema.SchemaValidator - Validating: configuration/feature-mapping
12:25:45 INFO cli.engine.schema.SchemaValidator - Validating: configuration/shared-config
12:25:45 INFO cli.engine.schema.SchemaValidator - Validating: epiphany-cluster - k8svalidate
12:25:45 INFO cli.engine.schema.SchemaValidator - Validating: configuration/kubernetes-master
12:25:45 ERROR cli.engine.schema.SchemaValidator - Failed validating: configuration/kubernetes-master
12:25:45 ERROR cli.engine.schema.SchemaValidator - 24856 is greater than the maximum of 24855

Failed validating 'maximum' in schema['properties']['specification']['properties']['advanced']['properties']['certificates']['properties']['expiration_days']:
    {'$id': '#/properties/specification/properties/advanced/properties/certificates/properties/expiration_days',
     'default': 365,
     'description': 'Days to make certificate be valid for.\n'
                    'For more explanation about the limit navigate to\n'
                    'https://groups.google.com/g/mailing.openssl.users/c/3kK_f0ywCZQ.',
     'maximum': 24855,
     'minimum': 1,
     'title': 'expiration_days schema',
     'type': 'integer'}

On instance['specification']['advanced']['certificates']['expiration_days']:
    24856
12:25:45 INFO cli.engine.schema.SchemaValidator - Step finished in: 0.11s
```

OK I get it, when having different data types it fails on merging, and all the validation is performed later.

**Review by przemyslavic — APPROVED** [review]

**Comment by przemyslavic** [comment]
However, I still believe that all validation should be executed before the terraform part.

**Review by erzetpe — APPROVED** [review]

**Pull request merged**
