### PR TITLE
Download grafana package from URL

### PR DESCRIPTION
**Pull request by to-bar**

### CODE REVIEW

**Review by seriva — DISMISSED** [review]

**Review by seriva — APPROVED** [review]

**Review by przemyslavic — APPROVED** [review]

**Comment by przemyslavic** [comment]
✔️ epicli apply: `AWS` / `Azure` x `RHEL` / `CentOS` / `Ubuntu` x64
✔️ epicli apply: `AWS` `CentOS` aarch64

**Pull request merged**
