### PR TITLE
Fix automated tests for Zookeeper

### PR DESCRIPTION
**Pull request by to-bar**
Starting from v3.5.3 Four Letter Words Zookeeper's commands need to be explicitly whitelisted to work. See `4lw.commands.whitelist` described in [cluster configuration section](https://zookeeper.apache.org/doc/r3.5.8/zookeeperAdmin.html#sc_clusterOptions) for details. Moving forward, Four Letter Words will be deprecated and the use of AdminServer is recommended instead.

### CODE REVIEW

**Review by przemyslavic — DISMISSED** [review]

**Review by erzetpe — APPROVED** [review]

**Review by sk4zuzu — APPROVED** [review]
:hippopotamus:

**Review by przemyslavic — DISMISSED** [review]

**Review by sk4zuzu — APPROVED** [review]
:thinking:

**Review by plirglo — APPROVED** [review]

**Review by sk4zuzu — APPROVED** [review]
😍

**Review by przemyslavic — APPROVED** [review]

**Pull request merged**
