### PR TITLE
Fix for RHUI client certificate expiration

### PR DESCRIPTION
**Pull request by plirglo**

### CODE REVIEW

**Review by seriva — APPROVED** [review]

**Review by atsikham — CHANGES_REQUESTED** [review]
There are 12 commits for a few changes, not all of them are necessary.

**Comment by seriva** [comment]
> There are 12 commits for a few changes, not all of them are necessary.

Mostly for testing I think, and that is why we squash when merging a branch. I don't see the need to change this.

**Comment by plirglo** [comment]
> There are 12 commits for a few changes, not all of them are necessary.

I will squash while merging.

**Review by atsikham — APPROVED** [review]

**Pull request merged**
