### PR TITLE
Truncate motd file on upgrade

### PR DESCRIPTION
**Pull request by atsikham**
Task #2494

### CODE REVIEW

**Review by przemyslavic — APPROVED** [review]

**Comment by przemyslavic** [comment]
Tested `apply` and `upgrade` on `Ubuntu`, `RHEL` and `CentOS`.
On a cluster upgraded from v1.1.0 to dev it shows `Epiphany version is 1.1.0`, is that correct? I assume it is because this is an upgrade, and not re-apply, but I want to make sure 😉

**Comment by atsikham** [comment]
@przemyslavic I think it should be discussed as I also don't know requirements, but I would change that during upgrade 😄

**Comment by przemyslavic** [comment]
@atsikham After discussion, we agreed that it would be good to have information about the original version that was installed and the version to which it was updated.

**Review by erzetpe — APPROVED** [review]

**Comment by atsikham** [comment]
> @atsikham After discussion, we agreed that it would be good to have information about the original version that was installed and the version to which it was updated.

It was discussed internally that what's is displayed there needs to be discussed after #1306 (PR #2650) is completed.

**Pull request merged**
