### PR TITLE
K8s upgrade tasks refactoring

### PR DESCRIPTION
**Pull request by atsikham**

### CODE REVIEW

**Review by cicharka — DISMISSED** [review]

**Comment by seriva** [comment]
@atsikham Would it make sense to also move the upgrade code to the actual Kubernetes component? As we have been doing for some of the other ones in previous upgrades already.

**Comment by atsikham** [comment]
> @atsikham Would it make sense to also move the upgrade code to the actual Kubernetes component? As we have been doing for some of the other ones in previous upgrades already.

I think yes, but this part is quite large and there are a few roles related to K8s, so for me the target structure is not clear. @to-bar started doing so in the scope of a separate collection, so I think these changes should be also consistent

**Review by seriva — DISMISSED** [review]

**Review by przemyslavic — APPROVED** [review]

**Review by cicharka — APPROVED** [review]

**Review by erzetpe — APPROVED** [review]

**Pull request merged**
