### PR TITLE
Fix for failing default merges... attempt 2

### PR DESCRIPTION
**Pull request by seriva**

### CODE REVIEW

**Review by rafzei — DISMISSED** [review]

**Review by mkyc — DISMISSED** [review]

**Review by to-bar — APPROVED** [review]

**Review by mkyc — APPROVED** [review]

**Review by rafzei — APPROVED** [review]

**Review by przemyslavic — APPROVED** [review]

**Comment by przemyslavic** [comment]
✔️ Tested the ability to change the default values for OS image, instance type (vm size) and disk size at different levels of default values.

**Pull request merged**
