### PR TITLE
[Upgrade] epicli may fail after re-running

### PR DESCRIPTION
**Pull request by to-bar**
- Do not clean up epirepo when skipping download
- Improve removing old files and images

### CODE REVIEW

**Review by seriva — DISMISSED** [review]

**Review by przemyslavic — DISMISSED** [review]

**Comment by przemyslavic** [comment]
Tested:
`epicli apply` -> `epicli upgrade` -> force stop `epicli upgrade` -> re-run `epicli upgrade` -> success 👍

**Review by przemyslavic — APPROVED** [review]

**Review by seriva — APPROVED** [review]

**Pull request merged**
