### PR TITLE
Use pki config from manifest for apiserver certificates

### PR DESCRIPTION
**Pull request by atsikham**
These changes are related to #1556, but as I knew about this configuration parameter only during #1595 implementation, PR is created now.

### CODE REVIEW

**Review by mkyc — COMMENTED** [review]
Is this related to some task?

**Comment by atsikham** [comment]
@mkyc it could be #1520, but it's not there because of the reason written in description. So I decided to fix that without any task.

**Review by mkyc — APPROVED** [review]
LGTM

**Review by sk4zuzu — APPROVED** [review]
LGTM

**Pull request merged**
