### PR TITLE
Patching cgroup drivers (switch to systemd)

### PR DESCRIPTION
**Pull request by sk4zuzu**

### CODE REVIEW

**Review by rafzei — DISMISSED** [review]
The fix was tested by the internal team, after merge we should perform similar stress tests.
Kudos MO!

**Review by atsikham — DISMISSED** [review]
LGTM

**Comment by sk4zuzu** [comment]
I found fatal problem during k8s upgrades so I had to reconsider my solution :) I believe it's correct now!

**Review by to-bar — DISMISSED** [review]
:kimono:

**Review by atsikham — APPROVED** [review]
🥇

**Review by rafzei — APPROVED** [review]

**Comment by sk4zuzu** [comment]
Please note this PR after testing should be backported at least to 0.9 and 0.8 and would be good also to do it for 0.7 and 0.6. :+1:

**Pull request merged**
