### PR TITLE
[Backport][1.1] Backport for (2124) (#2493)

### LINKED ISSUE #2580: [BACKPORT][v1.1] Add Internet connection test to download-requirements.sh

### PR DESCRIPTION
**Pull request by sbbroot**
* Add backport for #2493, #2538 and #2560

### CODE REVIEW

**Review by seriva — DISMISSED** [review]

**Comment by przemyslavic** [comment]
@sbbroot please update the changelog

**Comment by przemyslavic** [comment]
The changelog entry should not go into v1.1.0 that has already been released.

**Comment by przemyslavic** [comment]
Also not like that. This should go to v1.1.1.

**Review by przemyslavic — APPROVED** [review]

**Review by seriva — APPROVED** [review]

**Pull request merged**
