### PR TITLE
[Bug][Kafka] Incorrect number of brokers/queues available after scaling up/down

### PR DESCRIPTION
**Pull request by plirglo**
meta.properties is re-created by Kafka every time when service is starting and file does not exist. It contains broker.id and cluster.id which are shared between brokers using zookeeper.

### CODE REVIEW

**Review by seriva — APPROVED** [review]

**Comment by seriva** [comment]
I think this would be something we want backport to 1.0.x, 0.9.x and 0.8.x Lets not bother to 0.7.x as it will be deprecated soon.

**Review by przemyslavic — APPROVED** [review]

**Pull request merged**
