### PR TITLE
bump rabbitmq version from 3.7.10 to 3.8.3 #1395

### PR DESCRIPTION
**Pull request by ar3ndt**

### CODE REVIEW

**Comment by przemyslavic** [comment]
And what about existing clusters with deployments in version 3.7.10? Upgrading/patching?

**Comment by pyrkamarcin** [comment]
> And what about existing clusters with deployments in version 3.7.10? Upgrading/patching?

@ar3ndt correct me if I'm wrong, but there is no option to soft upgrade on this moment. Current upgrade process only patching image version on StatefulSet on memory manifest, then new version of pod has no created without manual delete old and lose data.

**Comment by ar3ndt** [comment]
> > And what about existing clusters with deployments in version 3.7.10? Upgrading/patching?
> 
> @ar3ndt correct me if I'm wrong, but there is no option to soft upgrade on this moment. Current upgrade process only patching image version on StatefulSet on memory manifest, then new version of pod has no created without manual delete old and lose data.

yeah that would be kinda problematic with gracefully bumping it while there might be data in the queues.
Lets hold on with this

**Comment by seriva** [comment]
Missing changelog entry.

**Comment by ar3ndt** [comment]
> My general question is: is that possible to have value `3.8.3` in some uber-vars? Can we have it from single place and then just change `3.7.10` to `3.8.3` in one line?

I think so, maybe by the way of modularisation task.

**Pull request merged**
