### PR TITLE
Switch to RHEL 8.4 for longer support

### PR DESCRIPTION
**Pull request by to-bar**

### CODE REVIEW

**Review by seriva — DISMISSED** [review]

**Review by plirglo — DISMISSED** [review]

**Comment by przemyslavic** [comment]
Tested offline mode:
:x: RHEL 8.4 fails on `repository : Create epirepo repository` task.
```
/var/tmp/epi-repository-setup-scripts/create-repository.sh: line 14: createrepo: command not found
```

:x: AlmaLinux 8.4 fails on `common : Install RedHat family packages` task.

```
Depsolve Error occurred: 
 Problem: package python36-3.6.8-38.module_el8.5.0+2569+5c5719bc.x86_64 requires python3-pip, but none of the providers can be installed
  - conflicting requests
  - nothing provides platform-python-pip = 9.0.3-20.el8 needed by python3-pip-9.0.3-20.el8.noarch
 ```

**Review by erzetpe — APPROVED** [review]

**Review by plirglo — APPROVED** [review]

**Comment by seriva** [comment]
Also needs a pull to dev once tested.

**Review by przemyslavic — APPROVED** [review]

**Comment by przemyslavic** [comment]
Let me merge it to have these changes in v2.0 branch and be able to test new PRs directly on this.

**Pull request merged**
