### PR TITLE
[Backport][1.0.1] Backport for (2124) (#2493)

### LINKED ISSUE #2579: [BACKPORT][v1.0] Add Internet connection test to download-requirements.sh

### PR DESCRIPTION
**Pull request by sbbroot**
* Add backport for #2493, #2538 and #2560

### CODE REVIEW

**Comment by przemyslavic** [comment]
@sbbroot please update the changelog

**Comment by przemyslavic** [comment]
❌@sbbroot It doesn't work properly.
```
Images to be downloaded:
     1  haproxy:2.2.2-alpine
     2  kubernetesui/dashboard:v2.0.3
     3  kubernetesui/metrics-scraper:v1.0.4
     4  registry:2
     5  hashicorp/vault-k8s:0.7.0
     6  vault:1.6.1
     7  apacheignite/ignite:2.9.1
     8  bitnami/pgpool:4.1.1-debian-10-r29
     9  brainsam/pgbouncer:1.12
    10  istio/pilot:1.8.1
    11  istio/proxyv2:1.8.1
    12  istio/operator:1.8.1
    13  jboss/keycloak:9.0.0
    14  rabbitmq:3.8.9
    15  k8s.gcr.io/kube-apiserver:v1.14.6
    16  k8s.gcr.io/kube-controller-manager:v1.14.6
    17  k8s.gcr.io/kube-proxy:v1.14.6
    18  k8s.gcr.io/kube-scheduler:v1.14.6
    19  k8s.gcr.io/coredns:1.3.1
    20  k8s.gcr.io/etcd:3.3.10
    21  k8s.gcr.io/pause:3.1
    22  coredns/coredns:1.5.0
    23  epiphanyplatform/flannel:v0.11.0-amd64
    24  epiphanyplatform/flannel:v0.11.0
    25  calico/cni:v3.8.1
    26  calico/kube-controllers:v3.8.1
    27  calico/node:v3.8.1
    28  calico/pod2daemon-flexvol:v3.8.1
    29  k8s.gcr.io/kube-apiserver:v1.15.10
    30  k8s.gcr.io/kube-controller-manager:v1.15.10
    31  k8s.gcr.io/kube-proxy:v1.15.10
    32  k8s.gcr.io/kube-scheduler:v1.15.10
    33  k8s.gcr.io/coredns:1.3.1
    34  k8s.gcr.io/etcd:3.3.10
    35  k8s.gcr.io/pause:3.1
    36  k8s.gcr.io/kube-apiserver:v1.16.7
    37  k8s.gcr.io/kube-controller-manager:v1.16.7
    38  k8s.gcr.io/kube-proxy:v1.16.7
    39  k8s.gcr.io/kube-scheduler:v1.16.7
    40  k8s.gcr.io/coredns:1.6.2
    41  k8s.gcr.io/etcd:3.3.15-0
    42  k8s.gcr.io/pause:3.1
    43  k8s.gcr.io/kube-apiserver:v1.17.4
    44  k8s.gcr.io/kube-controller-manager:v1.17.4
    45  k8s.gcr.io/kube-scheduler:v1.17.4
    46  k8s.gcr.io/kube-proxy:v1.17.4
    47  k8s.gcr.io/coredns:1.6.5
    48  k8s.gcr.io/etcd:3.4.3-0
    49  k8s.gcr.io/pause:3.1
    50  epiphanyplatform/flannel:v0.11.0-amd64
    51  epiphanyplatform/flannel:v0.11.0
    52  calico/cni:v3.11.2
    53  calico/cni:v3.12.0
    54  calico/kube-controllers:v3.11.2
    55  calico/node:v3.11.2
    56  calico/node:v3.12.0
    57  calico/pod2daemon-flexvol:v3.11.2
    58  calico/pod2daemon-flexvol:v3.12.0
    59  k8s.gcr.io/kube-apiserver:v1.17.7
    60  k8s.gcr.io/kube-controller-manager:v1.17.7
    61  k8s.gcr.io/kube-scheduler:v1.17.7
    62  k8s.gcr.io/kube-proxy:v1.17.7
    63  k8s.gcr.io/coredns:1.6.5
    64  k8s.gcr.io/etcd:3.4.3-0
    65  k8s.gcr.io/pause:3.1
    66  quay.io/coreos/flannel:v0.12.0-amd64
    67  quay.io/coreos/flannel:v0.12.0
    68  calico/cni:v3.15.0
    69  calico/kube-controllers:v3.15.0
    70  calico/node:v3.15.0
    71  calico/pod2daemon-flexvol:v3.15.0
    72  k8s.gcr.io/kube-apiserver:v1.18.6
    73  k8s.gcr.io/kube-controller-manager:v1.18.6
    74  k8s.gcr.io/kube-scheduler:v1.18.6
    75  k8s.gcr.io/kube-proxy:v1.18.6
    76  k8s.gcr.io/coredns:1.6.7
    77  k8s.gcr.io/etcd:3.4.3-0
    78  k8s.gcr.io/pause:3.2
    79  quay.io/coreos/flannel:v0.12.0-amd64
    80  quay.io/coreos/flannel:v0.12.0
    81  calico/cni:v3.15.0
    82  calico/kube-controllers:v3.15.0
    83  calico/node:v3.15.0
    84  calico/pod2daemon-flexvol:v3.15.0

Downloading image: haproxy:2.2.2-alpine
Crane command is: /shared/build/prepare_scripts/crane pull --insecure --format=legacy haproxy:2.2.2-alpine /shared/build/req/images/haproxy-2.2.2-alpine.tar
/shared/build/prepare_scripts/common.sh: line 47: docker_platform: unbound variable
```

**Comment by przemyslavic** [comment]
@sbbroot again you added a changelog entry to the already released version `v1.0.1`. It should be `v1.0.2`.

**Comment by przemyslavic** [comment]
There are still some issues when executing `download-requirements.sh` script without provided download directory (it should just show the `usage` message):
```
root@d25e5d87b50d:/# /shared/build/prepare_scripts_ubuntu_v1.0/download-requirements.sh
usage: ./download-requirements.sh <download_dir>
       ./download-requirements.sh /tmp/downloads
/shared/build/prepare_scripts_ubuntu_v1.0/common.sh: line 7: $1: unbound variable
```

as it is in develop:
```
root@d25e5d87b50d:/# /shared/build/prepare_scripts_ubu_develop/download-requirements.sh
usage:         ./download-requirements.sh <downloads_dir>
example:       ./download-requirements.sh /tmp/downloads
```

**Review by przemyslavic — APPROVED** [review]

**Review by mkyc — APPROVED** [review]

**Pull request merged**
