### PR TITLE
Elasticsearch upgrade improvements

### PR DESCRIPTION
**Pull request by to-bar**
- Wait for yellow status with additional conditions
- Handle copying certificate files on re-run when first host is skipped
- Store initial cluster status and assert it after upgrade

### CODE REVIEW

**Review by seriva — APPROVED** [review]
Looks good, just one questions about the retries of wait-for-node-to-join.yml and wait-for-shard-allocation.yml. This was tested with some data inside? As that might influence a mechanism like this.

**Comment by to-bar** [comment]
@seriva Good point. I tested upgrade only with really small amount of data and it was quick but I've chosen bigger numbers for `retries` just in case. The steps are optimized for performance but it would be cool to test upgrade of a cluster with bigger amount of data (with many indices).

**Review by atsikham — APPROVED** [review]
LGTM

**Pull request merged**
