### PR TITLE
Deterministic hosts order in hostgroup

### PR DESCRIPTION
**Pull request by sunshine69**
Tested by me. The behavior is now expected order of hosts in host group. The order is sorted by hostname as string sort and does not change in multiple re runs.

### CODE REVIEW

**Comment by przemyslavic** [comment]
@mkyc @seriva @to-bar 
I performed some testing on this PR. It works fine for `applying` and `re-applying` cluster configuration (tested on Azure and AWS).
Additionally it solves the issue #1702 on Azure. However, there may still be issues on AWS scaling components up, depending on which position the new host goes to.
I would introduce the change for Azure provider, and not necessarily for AWS.

**Comment by mkyc** [comment]
@przemyslavic can you please check upgrade scenario?

**Comment by mkyc** [comment]
We are closing it since its implemented in #2733

**Pull request closed without merging**
