### PR TITLE
Fixed rabbitmq dependencies for upgrade

### PR DESCRIPTION
**Pull request by atsikham**
Task #1956

### CODE REVIEW

**Review by sk4zuzu — APPROVED** [review]
LGTM

**Review by seriva — APPROVED** [review]

**Comment by seriva** [comment]
SHould also be done for the 0.9.0 branch.

**Comment by atsikham** [comment]
> SHould also be done for the 0.9.0 branch.

Will be synchronized by @to-bar from develop.

**Comment by przemyslavic** [comment]
Successfully upgraded RabbitMQ (from epicli version 0.8 to develop).

**Review by przemyslavic — APPROVED** [review]

**Pull request merged**
