### PR TITLE
ARM support for Ignite and RabbitMQ applications

### PR DESCRIPTION
**Pull request by atsikham**

### CODE REVIEW

**Review by seriva — APPROVED** [review]

**Comment by mkyc** [comment]
Shouldn't we also mention in change log and in components that we upgrade Istio version?

**Comment by atsikham** [comment]
> Shouldn't we also mention in change log and in components that we upgrade Istio version?

There is only Ignite changes, version was just changed in docs to be the same as we use.

**Comment by mkyc** [comment]
> > Shouldn't we also mention in change log and in components that we upgrade Istio version?
> 
> There is only Ignite changes, version was just changed in docs to be the same as we use.

Ohhh ... sorry for typo, I meant ignite. Yeah I just checked that versions are correct.

**Review by seriva — CHANGES_REQUESTED** [review]
Does this actually make the change for Redhat?

**Comment by atsikham** [comment]
> Does this actually make the change for Redhat?

Good catch

**Review by mkyc — APPROVED** [review]

**Review by to-bar — APPROVED** [review]

**Pull request merged**
