### PR TITLE
Fix containerd upgrade #3006

### PR DESCRIPTION
**Pull request by cicharka**
Provides fix for [upgrade bug related to containerd installation](https://github.com/epiphany-platform/epiphany/issues/3006).

* containerd upgrade moved from upgrade tasks to tasks/upgrade/main.yml under containerd role

* for containerd task, during upgrade procedure there is downgrade of containerd.io package possibility

* for docker tasks, containerd.io packages also can be downgraded, in order to fix problem with versioning

* changing container runtime in k8s from docker to contianerd now include also tasks for draining the nodes and patching statesfulsets. After replacement, waiting for k8s readiness is also included

* tasks that needs to be refactored are included in [refactoring ticket](https://github.com/epiphany-platform/epiphany/issues/3048)

### CODE REVIEW

**Review by seriva — DISMISSED** [review]

**Comment by cicharka** [comment]
I would also create a separate PR that will add upgrade status flags.

Another thing is that [remove Docker part](https://github.com/epiphany-platform/epiphany/pull/3024/files#diff-c76dd0497c3c204c02c67529c5b233190b6e603a3c199dc4df31f2518ea07b09R10) is quite dangerous -> if it will succeed, but containerd will not be configure as replacement in kubernetes, it will break CRI that is set in kubernetes. Additionally it stops kubelet so in case of failure it will not be restarted.
What do you think about it?

**Review by erzetpe — DISMISSED** [review]

**Review by erzetpe — DISMISSED** [review]

**Review by seriva — DISMISSED** [review]

**Comment by cicharka** [comment]
After another round of conversations (with @to-bar and @rafzei ) I will adapt upgrades to allow downgrades to specific versions of contaienrd.io while taking care of running processes. Temporarily I will change this PR to draft.

**Comment by cicharka** [comment]
Changes introduced since last [commit](https://github.com/epiphany-platform/epiphany/pull/3024/commits/b1f02be1717003099a01203fe8330a25881fe456):
- upgrade tasks now will be skipped if containerd.io packaged version is already satisfied
- the same for docker packages - upgrade tasks will be skipped if versions satisfied
- containerd.io package can be now downgraded to specified version
- if any package is upgraded/downgraded, configuration tasks will be executed, otherwise they will be skipped - doesn't matter if it only changed one package, I kept all of the tasks that were previously there during upgrade stage
- upgrade status flag file was introduced only for docker upgrade role -> it can be also added to containerd upgrade role altought it includes also docker removal. I was not able to come with better structure there, and maybe these docker_removed and containerd_updated facts can be refactored into nicer code
- I kept debug tasks for Print version of docker server, as they were already there, but please comment if they are meaningful there
- not tested it extensively, only apply and upgrade, spec tests passed in both cases

**Review by erzetpe — DISMISSED** [review]

**Review by seriva — DISMISSED** [review]

**Comment by przemyslavic** [comment]
Upgrade from v1.0 to 2.0.0dev fails on RHEL and Ubuntu:
```
2022-03-16T14:12:41.8120729Z[38;21m14:12:41 INFO cli.src.ansible.AnsibleCommand - TASK [docker : Stop kubelet before Docker update] ******************************
2022-03-16T14:12:43.0225522Z[31;21m14:12:43 ERROR cli.src.ansible.AnsibleCommand - fatal: [ci-13todevazrhflannel-repository-vm-0]: FAILED! => {"changed": false, "msg": "Could not find the requested service kubelet: host"}

```
Upgrade from v1.3 to 2.0.0dev fails on RHEL for the same reason.

**Review by atsikham — DISMISSED** [review]

**Comment by przemyslavic** [comment]
:x: Single machine upgrade from v1.0 fails on RHEL:
```
pulling image: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService\"\n, error: exit status 1\n\t[ERROR ImagePull]: failed to pull image ci-10sndevazrhflannel-single-machine-vm-0:5000/k8s.gcr.io/kube-controller-manager:v1.19.15
```
```
2022-03-18T10:36:58.8318007Z[31;21m10:36:58 ERROR cli.src.ansible.AnsibleCommand - fatal: [ci-10sndevazrhflannel-single-machine-vm-0]: FAILED! => {"attempts": 20, "changed": false, "cmd": ["kubeadm", "upgrade", "apply", "-y", "v1.19.15"], "delta": "0:00:03.838292", "end": "2022-03-18 10:36:58.625611", "msg": "non-zero return code", "rc": 2, "start": "2022-03-18 10:36:54.787319", "stderr": "[preflight] Some fatal errors occurred:\n\t[ERROR ImagePull]: failed to pull image ci-10sndevazrhflannel-single-machine-vm-0:5000/k8s.gcr.io/kube-apiserver:v1.19.15: output: time=\"2022-03-18T10:36:58Z\" level=fatal msg=\"pulling image: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService\"\n, error: exit status 1\n\t[ERROR ImagePull]: failed to pull image ci-10sndevazrhflannel-single-machine-vm-0:5000/k8s.gcr.io/kube-controller-manager:v1.19.15: output: time=\"2022-03-18T10:36:58Z\" level=fatal msg=\"pulling image: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService\"\n, error: exit status 1\n\t[ERROR ImagePull]: failed to pull image ci-10sndevazrhflannel-single-machine-vm-0:5000/k8s.gcr.io/kube-scheduler:v1.19.15: output: time=\"2022-03-18T10:36:58Z\" level=fatal msg=\"pulling image: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService\"\n, error: exit status 1\n\t[ERROR ImagePull]: failed to pull image ci-10sndevazrhflannel-single-machine-vm-0:5000/k8s.gcr.io/kube-proxy:v1.19.15: output: time=\"2022-03-18T10:36:58Z\" level=fatal msg=\"pulling image: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService\"\n, error: exit status 1\n\t[ERROR ImagePull]: failed to pull image ci-10sndevazrhflannel-single-machine-vm-0:5000/k8s.gcr.io/pause:3.2: output: time=\"2022-03-18T10:36:58Z\" level=fatal msg=\"pulling image: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService\"\n, error: exit status 1\n\t[ERROR ImagePull]: failed to pull image ci-10sndevazrhflannel-single-machine-vm-0:5000/k8s.gcr.io/etcd:3.4.13-0: output: time=\"2022-03-18T10:36:58Z\" level=fatal msg=\"pulling image: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService\"\n, error: exit status 1\n\t[ERROR ImagePull]: failed to pull image ci-10sndevazrhflannel-single-machine-vm-0:5000/k8s.gcr.io/coredns:1.7.0: output: time=\"2022-03-18T10:36:58Z\" level=fatal msg=\"pulling image: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService\"\n, error: exit status 1\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`\nTo see the stack trace of this error execute with --v=5 or higher", "stderr_lines": ["[preflight] Some fatal errors occurred:", "\t[ERROR ImagePull]: failed to pull image ci-10sndevazrhflannel-single-machine-vm-0:5000/k8s.gcr.io/kube-apiserver:v1.19.15: output: time=\"2022-03-18T10:36:58Z\" level=fatal msg=\"pulling image: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService\"", ", error: exit status 1", "\t[ERROR ImagePull]: failed to pull image ci-10sndevazrhflannel-single-machine-vm-0:5000/k8s.gcr.io/kube-controller-manager:v1.19.15: output: time=\"2022-03-18T10:36:58Z\" level=fatal msg=\"pulling image: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService\"", ", error: exit status 1", "\t[ERROR ImagePull]: failed to pull image ci-10sndevazrhflannel-single-machine-vm-0:5000/k8s.gcr.io/kube-scheduler:v1.19.15: output: time=\"2022-03-18T10:36:58Z\" level=fatal msg=\"pulling image: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService\"", ", error: exit status 1", "\t[ERROR ImagePull]: failed to pull image ci-10sndevazrhflannel-single-machine-vm-0:5000/k8s.gcr.io/kube-proxy:v1.19.15: output: time=\"2022-03-18T10:36:58Z\" level=fatal msg=\"pulling image: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService\"", ", error: exit status 1", "\t[ERROR ImagePull]: failed to pull image ci-10sndevazrhflannel-single-machine-vm-0:5000/k8s.gcr.io/pause:3.2: output: time=\"2022-03-18T10:36:58Z\" level=fatal msg=\"pulling image: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService\"", ", error: exit status 1", "\t[ERROR ImagePull]: failed to pull image ci-10sndevazrhflannel-single-machine-vm-0:5000/k8s.gcr.io/etcd:3.4.13-0: output: time=\"2022-03-18T10:36:58Z\" level=fatal msg=\"pulling image: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService\"", ", error: exit status 1", "\t[ERROR ImagePull]: failed to pull image ci-10sndevazrhflannel-single-machine-vm-0:5000/k8s.gcr.io/coredns:1.7.0: output: time=\"2022-03-18T10:36:58Z\" level=fatal msg=\"pulling image: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService\"", ", error: exit status 1", "[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`", "To see the stack trace of this error execute with --v=5 or higher"], "stdout": "[upgrade/config] Making sure the configuration is correct:\n[upgrade/config] Reading configuration from the cluster...\n[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'\n[preflight] Running pre-flight checks.\n[upgrade] Running cluster health checks\n[upgrade/version] You have chosen to change the cluster version to \"v1.19.15\"\n[upgrade/versions] Cluster version: v1.18.6\n[upgrade/versions] kubeadm version: v1.19.15\n[upgrade/prepull] Pulling images required for setting up a Kubernetes cluster\n[upgrade/prepull] This might take a minute or two, depending on the speed of your internet connection\n[upgrade/prepull] You can also perform this action in beforehand using 'kubeadm config images pull'", "stdout_lines": ["[upgrade/config] Making sure the configuration is correct:", "[upgrade/config] Reading configuration from the cluster...", "[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'", "[preflight] Running pre-flight checks.", "[upgrade] Running cluster health checks", "[upgrade/version] You have chosen to change the cluster version to \"v1.19.15\"", "[upgrade/versions] Cluster version: v1.18.6", "[upgrade/versions] kubeadm version: v1.19.15", "[upgrade/prepull] Pulling images required for setting up a Kubernetes cluster", "[upgrade/prepull] This might take a minute or two, depending on the speed of your internet connection", "[upgrade/prepull] You can also perform this action in beforehand using 'kubeadm config images pull'"]}
```

:x: Single machine upgrade from v1.3 RHEL
There were no errors in the upgrade procedure but the node is misconfigured (docker is used as a container runtime):
- containerd service is not enabled
- `crictl version` command returns docker and not containerd
- `kubectl get nodes` shows `docker://20.10.8` 

:x: Upgrade from v1.3 (1 master + 2 nodes; RHEL and Ubuntu) - there is an issue with RabbitMQ deployment after the upgrade.
The replicas cannot communicate with each other. After executing `kubectl rollout restart -n=queue statefulset rabbitmq-cluster`, the application starts working properly.

**Review by erzetpe — DISMISSED** [review]

**Review by atsikham — DISMISSED** [review]

**Review by seriva — DISMISSED** [review]

**Review by rafzei — DISMISSED** [review]
LGTM

**Review by przemyslavic — APPROVED** [review]

**Review by atsikham — APPROVED** [review]

**Pull request merged**
