### PR TITLE
Update kafka to version 2.6.1

### PR DESCRIPTION
**Pull request by sunshine69**
Upstream update

### CODE REVIEW

**Review by atsikham — CHANGES_REQUESTED** [review]
Changelog and COMPONENTS.md must be updated

**Comment by seriva** [comment]
@sunshine69 Can you look at the requested changes?

**Comment by mkyc** [comment]
Since it is quite old and doesn't include upgrade procedure we probably want to close it without merge, but we should discuss it before we do.

**Comment by mkyc** [comment]
We agreed together that it needs to be closed.

**Pull request closed without merging**
