### PR TITLE
Upgraded logstash to v7.12.0

### PR DESCRIPTION
**Pull request by atsikham**
Task #2116. This change is done as there is a bug for ARM in previous Logstash version we had. New version brings bundled JDK, so it's not necessary to install it additionally.

### CODE REVIEW

**Comment by przemyslavic** [comment]
✔️ tested on CentOS ARM, it works fine
✔️ tested on Ubuntu/RHEL/CentOS x AWS/Azure x64
2. @atsikham please update component version and docs https://github.com/epiphany-platform/epiphany/blob/ARM/docs/home/howto/LOGGING.md#how-to-export-elasticsearch-data-to-csv-format (logstash version, input/output plugins version, path to `lib/logstash/inputs/elasticsearch.rb` file.

**Review by seriva — CHANGES_REQUESTED** [review]
Also update the version here: https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/COMPONENTS.md

**Review by rafzei — APPROVED** [review]
LGTM

**Review by przemyslavic — APPROVED** [review]

**Review by seriva — APPROVED** [review]

**Pull request merged**
