### PR TITLE
[BACKPORTS][v1.1.0] - #2478 and #2480

### PR DESCRIPTION
**Pull request by seriva**
This pull is for backport issues #2478 and #2480. Did both of them in the same pull as some code was overlapping. Like in the linked related PR below, there is no need for reviewing all validation YAMLs as they should by mainly tested by @przemyslavic .

Issue: #2478
Backport for issue: #195, #2425
Related PR: #2470, #2474

issue: #2480
Backport for issue: #1294, #1370
Related PR: #2465

Also included issue #1296 with related PR #2552, as there where a minor addition for #2425

### CODE REVIEW

**Comment by rafzei** [comment]
Should we hang on with review/merge till @przemyslavic  will be able to start testing?

**Comment by seriva** [comment]
> Should we hang on with review/merge till @przemyslavic will be able to start testing?

Most of this code was already tested in:  #2465, #2470, #2474. There are some small differences because of the versions but I would be fine with merging it after review and let @przemyslavic test it afterwards. Any issues can be addressed in separate tasks. But that is my opinion:)

**Review by rafzei — DISMISSED** [review]

**Review by erzetpe — DISMISSED** [review]

**Comment by przemyslavic** [comment]
Additional fix required https://github.com/epiphany-platform/epiphany/issues/1294#issuecomment-900194372.

**Review by erzetpe — DISMISSED** [review]

**Review by rafzei — DISMISSED** [review]

**Review by rafzei — DISMISSED** [review]

**Review by erzetpe — DISMISSED** [review]

**Review by rafzei — DISMISSED** [review]

**Review by przemyslavic — DISMISSED** [review]

**Comment by przemyslavic** [comment]
@seriva Same as in comment https://github.com/epiphany-platform/epiphany/pull/2481#issuecomment-934401797, some validations are missing (e.g. `specification.clustered` for logging component). In my opinion, it would be nice to refresh all the validations so that they are consistent with what we have in a given branch.

**Comment by seriva** [comment]
Good point, ill rerun the validation process for all documents tomorrow on both branches. Should be like an hour.

**Comment by seriva** [comment]
@przemyslavic Fixed a bunch of minor issues across multiple validation files.

/azp run

**Review by przemyslavic — APPROVED** [review]

**Review by sbbroot — APPROVED** [review]

**Pull request merged**
